In [10]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt


df = pd.read_csv('D:\Projects\ML (University)\lab5_1\Iris.csv')


#print(df.head(10))
print(df.shape)
df.isna().sum()

(150, 6)


Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [27]:
# Load the data, make sure to set the separator correctly.
df = pd.read_csv('D:\Projects\ML (University)\lab5_1\Iris.csv')

# Drop the 'Id' column right after loading the data.
df = df.drop(columns=['Id'])

# Now, you can define your data and target.
data = df.iloc[:,:-1]  # All columns except the last one.
target = df.iloc[:,-1]  # Just the last column.

# Now if you print data and target, you should get the actual DataFrame and Series you expect.
print(data.head())
print(target.head())

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2
0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object


In [61]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score


df = pd.read_csv('D:\Projects\ML (University)\lab5_1\Iris.csv', sep=',')


df = df.drop(columns=['Id'])


X = df.iloc[:,:-1]
Y = df.iloc[:,-1]


X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=42)


log = LogisticRegression()


log.fit(X_train, Y_train)


predictions = log.predict(X_test)

cnf = confusion_matrix(predictions, Y_test)
print(cnf)


comparison_df = pd.DataFrame(list(zip(Y_test, predictions)), columns=['Actual', 'Predicted'])
print(comparison_df)

accuracy = accuracy_score(Y_test, predictions)
print(f"Accuracy: {accuracy}")






[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]
             Actual        Predicted
0   Iris-versicolor  Iris-versicolor
1       Iris-setosa      Iris-setosa
2    Iris-virginica   Iris-virginica
3   Iris-versicolor  Iris-versicolor
4   Iris-versicolor  Iris-versicolor
5       Iris-setosa      Iris-setosa
6   Iris-versicolor  Iris-versicolor
7    Iris-virginica   Iris-virginica
8   Iris-versicolor  Iris-versicolor
9   Iris-versicolor  Iris-versicolor
10   Iris-virginica   Iris-virginica
11      Iris-setosa      Iris-setosa
12      Iris-setosa      Iris-setosa
13      Iris-setosa      Iris-setosa
14      Iris-setosa      Iris-setosa
15  Iris-versicolor  Iris-versicolor
16   Iris-virginica   Iris-virginica
17  Iris-versicolor  Iris-versicolor
18  Iris-versicolor  Iris-versicolor
19   Iris-virginica   Iris-virginica
20      Iris-setosa      Iris-setosa
21   Iris-virginica   Iris-virginica
22      Iris-setosa      Iris-setosa
23   Iris-virginica   Iris-virginica
24   Iris-virginica   Iris-virginica
2